name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 30

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.85.0
          components: clippy, rustfmt

      - name: Enable Rust dependency caching
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v1-rust

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run linter
        run: cargo clippy -- --deny warnings

      - name: Build
        run: |
          cargo install dioxus-cli@0.6.3
          dx bundle --platform web

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/dx/dcmfx_playground/release/web/public
